
spring:
#  profiles:
#      active: raja
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: root
    hikari:
      minimum-idle: 10
      maximum-pool-size: 1000
#      include: uat



