
# In this one yml file we are providing data for all the profiles and also activating one specific profile


spring:
  profiles:
    active: test

---

spring:
   config:
      activate:
         on-profile: dev
   datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql:///spring_factory
      username: root
      password: Raja@123
      dbcp2:
          initial-size: 10
          max-total: 100
      type: org.apache.commons.dbcp2.BasicDataSource

---

spring:
    config:
        activate:
            on-profile: test
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql:///spring_factory
        username: root
        password: Raja@123
        type: com.mchange.v2.c3p0.ComboPooledDataSource
        c3p0:
            min-pool-size: 10
            max-pool-size: 100


---

spring:
    config:
        activate:
           on-profile: uat
    datasource:
        driver-class-name: oracle.jdbc.driver.OracleDriver
        url: jdbc:oracle:thin:@localhost:1521:xe
        username: system
        password: root
        oracleucp:
              min-pool-size: 10
              max-pool-size: 100
        type: oracle.ucp.jdbc.PoolDataSource

---

spring:
    config:
        activate:
            on-profile: prod
    datasource:
        driver-class-name: oracle.jdbc.driver.OracleDriver
        url: jdbc:oracle:thin:@localhost:1521:xe
        username: system
        password: root
        hikari:
           minimum-idle: 10
           maximum-pool-size: 100
        type: com.zaxxer.hikari.HikariDataSource



    